---

#services:
    #flask-app:
       # build:
            #context: ./
        #    dockerfile: ./Dockerfile
       # image: website/flask-helloworld:1.0
       # container_name: flask_container
       # ports:
         #   - "5555:5555"

services:
  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: website/flask-helloworld:1.0
    container_name: flask_container
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=analyze_data.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5555 --debug